# -*- coding: utf-8 -*-
"""for

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kKEbGSFxzKeyQcTcLp3Dfb9sl8LDGPA5

# FOR

1)	 Faça um programa que leia 5 números e informe o maior número.
"""

maior_numero = 0
for i in range(5):
  x = int(input("Digite um valor: "))
  if x > maior_numero:
    maior_numero = x

print(maior_numero)

"""2)	Faça um programa que verifique e mostre os números entre 1.000 e 2.000 (inclusive) que, quando divididos por 11 produzam resto igual a 2."""

numero = 0
for n in range(1000, 2001):

 if n % 11/2:

  print(n)

"""3)	Faça um programa que leia 5 números e informe a soma e a média dos números."""

soma = 0
for n in range(5):
  x = float(input(f"Digite o {n+1}° numero: "))

  soma += x
  media = soma/5

print(f"o total é {soma}, e a média é {media}")

"""4)	 Faça um programa que receba um número e usando laços de repetição calcule e mostre a tabuada desse número."""

contador = float(input("Digite um numero: "))
print(f"Tabuada do numero {contador}")
for i in range(1,11):
  print(f"{contador} x {i} = {contador * i}")

"""5)	Faça um programa que mostre as tabuadas dos números de 1 a 10 usando laços de repetição."""

for n1 in range(1,11):
  for n2 in range(1,11):
    print(f"{n1} x {n2} = {n1 * n2}")

"""6)	Faça um programa que imprima na tela os números de 1 a 20, um abaixo do outro. Depois modifique o programa para que ele mostre os números um ao lado do outro."""

for contador in range(1,21):
  print(contador)

"""7)	 Faça um programa que imprima na tela apenas os números ímpares entre 1 e 50."""

for impar in range(1,51):
  if impar % 2 != 0:
    print(impar)

"""8)	Faça um programa que receba dois números inteiros e gere os números inteiros que estão no intervalo compreendido por eles."""

n1 = int(input("Digite o primeiro numero: "))
n2 = int(input("Digite o segundo numero: "))

for contador in range(n1+1, n2):
 print(contador)

"""9)	Uma loja deseja cadastrar 5 clientes e verificar se o faturamento da loja foi superior a loja B (faturamento = 54000). Se o faturamento atingir esse valor mostre na tela uma mensagem contendo em quanto foi superado o faturamento."""

lojaB = 54000
lojaA = 0

for i in range(5):
  valor = int(input("Digite o valor: "))
  lojaA += valor
if lojaA > lojaB:
  print(f"O faturamento da lojaA superou o faturamento da lojaB em {lojaA-lojaB}")

elif lojaA == lojaB:
  print("O faturamento da lojaA é igual ao faturamento da lojaB")
  print("O faturamento das lojas foram iguais.")

else:
  print(f"O faturamento da lojaA nao superou o faturamento da lojaB, falta {lojaB-lojaA}")

"""10)	 Faça um programa que peça 10 números inteiros, calcule e mostre a quantidade de números pares e a quantidade de números impares."""

impar = 0
par = 0

for i in range(10):
    number = int(input("Digite um valor: "))
    if number % 2 != 0:
        impar += 1
    if number % 2 == 0:
        par += 1

print(f"Numeros Impares: {impar}, Numeros Pares: {par}")

"""11) A) Um funcionário de uma empresa recebe aumento salarial anualmente, sabe-se que:

Esse funcionário foi contratado em 1995, com salário inicial de R$ 1.000,00; Em 1996 recebeu aumento de 1,5% sobre seu salário inicial; A partir 1997 (inclusive), os aumentos salariais sempre correspondem ao dobro do percentual do ano anterior. Faça um programa que determine o salário atual desse funcionário. Após concluir isto, altere o programa permitindo que o usuário digite o salário inicial do funcionário.

"""

initial = 1000
glow = 1.5 / 100

for i in range(1996,2024+1):
 initial += initial*glow
glow *= 2

print(f"O salario atual está em: {initial:,.2f}")

"""11) B) Após a conclusào do exercicio anterior, altere o programa permitindo que o usuário digite o salário inicial do funcionário."""

initial = float(input("Digite o seu salario inicial: "))
glow = 1.5/100

for year in range(1996,2024+1):
 initial += initial*glow
glow *= 2

print(f"O seu salario atual está em: {initial:,.2f}")

"""12)	 Faça um programa que peça uma nota, entre zero e dez. Mostre uma mensagem caso o valor seja inválido e continue pedindo até que o usuário informe um valor válido."""

for i in range(15):
  nota = int(input("Digite uma nota entre 0 e 10: "))
  if nota < 0 or nota >10:
    print(f"Nota invalida: {nota}")
  else:
    print(f"Nota Válida: {nota}")

"""13)	 Uma loja tem uma política de descontos de acordo com o valor da compra do cliente. Os descontos começam acima dos RS 500. A cada 100 reais acima dos RS 500,00 o cliente ganha 1% de desconto cumulativo até 25%.

Por exemplo: RS 500 = 1% || RS 600,00 = 2% ... etc...

Faça um programa que exiba essa tabela de descontos no seguinte formato:

valor da compra – porcentagem de desconto – valor final

"""

valor = float(input("Digite o valor da compra: "))
contagem = 1

if valor >= 600 and contador:
  reduzido = valor - 500
  if reduzido >=100 or contagem <= 24:
   for x in range(200):
    contagem += 1
    reduzido -= 100
    if reduzido < 100 or contagem == 24:
      break

porcentagem = contagem/100
desconto = valor*porcentagem
final = valor - desconto
print(f"O produto de R$ {valor:,.2f} ficará a partir de R$ {final} com {contagem:.0f}% de desconto.")

"""14)	Faça um programa que receba a idade de 15 pessoas e que calcule e mostre:

a) A quantidade de pessoas em cada faixa etária;

b) A porcentagem de pessoas na primeira e na última faixa etária, com relação ao total de pessoas:
* Até 15 anos
* De 16 a 30 anos
* De 31 a 45 anos
*	De 46 a 60 anos
*	Acima de 61 anos

"""

ate15 = 0
de16a30 = 0
de31a45 = 0
de46a60 = 0
alemde61 = 0
total = 15

for i in range(15):
    idade = int(input(f"Digite a idade da {i+1}° pessoa: "))
    if idade <= 15:
        ate15 += 1
    elif 16 <= idade <= 30:
        de16a30 += 1
    elif 31 <= idade <= 45:
        de31a45 += 1
    elif 46 <= idade <= 60:
        de46a60 += 1
    else:
        alemde61 += 1

print(f"Até 15 anos: {ate15} pessoa(as), ({(ate15/total)*100:,.2f}%) ")
print(f"De 16 a 30 anos: {de16a30} pessoa(as), ({(de16a30/total)*100:,.2f}%) ")
print(f"De 31 a 45 anos: {de31a45} pessoa(as), ({(de31a45/total)*100:,.2f}%) ")
print(f"De 46 a 60 anos: {de46a60} pessoa(as), ({(de46a60/total)*100:,.2f}%) ")
print(f"Além de 61 anos: {alemde61} pessoa(as), ({(alemde61/total)*100:,.2f}%) ")

"""15) Faça um programa que peça dois números, base e expoente, calcule e mostre o primeiro número elevado ao segundo número. Não utilize a função de potência da linguagem."""

base = float(input("Digite a base: "))
expoente = int(input("Digite o expoente: "))
result = 1

for i in range(expoente):
  if base == 1:
    result = base
  else:
    result*= base

print({result})

"""16) Faça um programa que mostre todos os primos entre 1 e N sendo N um número inteiro fornecido pelo usuário. O programa deverá mostrar também o número de divisões que ele executou para encontrar os números primos. Serão avaliados o funcionamento, o estilo e o número de testes (divisões) executados."""

n = int(input("Digite um númeo: "))

for numerotestado in range(1, n+1):
  for numerodivisor in range(numerotestado):
    print(f"{numerotestado}/{numerodivisor+1} = {numerotestado%(numerodivisor+1)}")

  if numerotestado % (numerodivisor+1) == 0:
    if 1 != numerodivisor+1 != numerotestado:
      print("Nao é primo")
      break
  elif numerodivisor+1 == numerotestado:
    print("É primo")