# -*- coding: utf-8 -*-
"""Exercises_While

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MPJQRboi9fAT5WJvrqiC3OzFCRyVQcPm

# Exercicios de While

1) Faça um programa que peça uma nota de 0 a 10. Mostre uma mensagem caso o valor seja ínvalido e continue pedindo até que o usuário que informe uma nota válida.
"""

nota = float(input("Digite uma nota de 0 a 10: "))
while nota > 10 or nota < 0:
  nota = float(input("Digite uma nota válida: "))

print(f"Nota: {nota}")

"""2) Faça um programa que leia um nome de usuário e a sua senha e não aceite a
senha igual ao nome do usuário, mostrando uma mensagem de erro e voltando
a pedir as informações.
"""

usuario = input("Digite um Usuário: ")
senha = input("Digite uma Senha: ")

while usuario == senha:
  print("O usuário e a senha precisam ser diferentes. Por Favor, insira os dados novamente: ")
  usuario = input("Digite um Usuário: ")
  senha = input("Digite uma Senha: ")

print("Cadastro Concluído")

"""3) Escreva um programa que conte de 1 a 10 e imprima cada número."""

numero = 1

while numero <=10:
  print(f"Numero: {numero}")
  numero += 1

"""4) Escreva um programa que imprima os números pares de 1 a 20."""

numero = 2

while numero <=20:
  print(f"Número par: {numero}")
  numero += 2

"""5) Escreva um programa que solicite ao usuário que insira um número e, em
seguida, imprima todos os números de 1 até esse número.
"""

numero = int(input("Digite um número: "))
contador = 1

while contador <= numero:
  print(f"Números: {contador}")
  contador += 1

"""6) Escreva um programa que solicite ao usuário que insira um número e, em
seguida, imprima todos os números pares de 2 até esse número.
"""

numero = int(input("Digite um número: "))
contador = 2

while contador <= numero:
  print(f"Números pares: {contador}")
  contador += 2

"""7) Escreva um programa que solicite ao usuário que insira um número e, em
seguida, imprima a tabuada desse número até 10.
"""

numero = int(input("Digite um numero: "))

contador = 1

while contador <=10:
  resultado = numero * contador
  print(f"{numero} X {contador} = {resultado}")
  contador +=1

"""8) Escreva um programa que solicite ao usuário que insira uma senha. O
programa deve continuar solicitando a senha até que o usuário insira a senha
correta.
"""

senha = 212

digit = int(input("Digite a senha: "))
while digit != senha:
    print("Senha Incorreta, insira a senha correta: ")
    digit = int(input("Digite a senha: "))

print("Senha Correta")

"""9) Escreva um programa que calcule a média de uma lista de números fornecida
pelo usuário.
"""

soma = 0
contador = 0

itens = int(input("Digite a quantidade de produtos: "))

while contador != itens:
  valores = int(input("Digite o valor: "))
  soma += valores
  contador += 1
  media = soma/itens

print(f"O valor médio dos produtos é de: {media}")

"""10) Escreva um programa que solicite ao usuário que insira números até que ele
insira o número 0. Em seguida, imprima a soma de todos os números inseridos.
"""

numero = int(input("Digite um número: "))
total = 0

while numero != 0:
  total += numero
  numero = int(input("Digite um número: "))

print(f"A soma dos números digitados foi de: {total}")

"""11) Escreva um programa que solicite ao usuário que insira números até que ele
insira um número negativo. Em seguida, imprima o maior número inserido.
"""

maior_numero = 0
numero = int(input("Digite um valor: "))

while numero >=0:
  numero = int(input("Digite um valor: "))
  if numero > maior_numero:
    maior_numero = numero

print(f"O maior número é {maior_numero}")