# -*- coding: utf-8 -*-
"""Desafio

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16H3TCypwRrCUqZdv0Vuh4DOalyo1PZQR
"""

import random
numero_aleatorio = random.randint(0,101)
tentativa = 0
print("                       BEM VINDO AO GAME ACERTE O NUMERO, VAMOS COMEÇAR?      ")
print(                             )
print( )

for i in range (10):
  tentativa = int(input(f"faça a sua {i+1}° tentativa:  "))
if tentativa == numero_aleatorio:
    print("SUCESSO!!! você acertou o numero aleaório")
else:
  print("10 tentativas incorretas")
print(f"INSUCESSO, o numero aleatório era {numero_aleatorio}"