# -*- coding: utf-8 -*-
"""DESAFIO

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OObseT2_0XTueUHHF9Z5GlBRibwKhC3i

# Desafio de "for" e "if/else".

Exercicios que eu (Gabriel Santos) elaborei a pedido do Prof Caique e da Prof Jessica.

* 2 exercicios usando "for"

* 2 exercicios usando "if/else"

# FOR

1) Calculadora de Nota Média Anual:

  Faça um código que peça ao usuário digitar 4 notas de 0 a 10, do 1º ao 4º bimestre, e depois mostre sua nota média, e se a nota média for maior ou igual a 6 mostre “Aprovado”. Senão “Reprovado”.
"""

notatotal = 0
for nota in range(4):
    n = int(input(f"Digite a {nota+1}º nota: "))

    notatotal += n
    media = notatotal/4

if media >= 6:
  print(f"A sua nota média é: {media}, Você está Aprovado(a).")
else:
  print(f"A sua nota média é: {media}, Você esta Reprovado(a).")

"""2) Calculadora com Conversor de Moeda:

  Faça um código que peça ao usuário que ele digite o valor de 5 compras em dólar e em sequência mostra o total da compra em dólar e o mesmo convertido para real.
"""

valortotal = 0
for valores in range(5):
  v = int(input(f"Digite o valor da {valores+1}º compra em dolar: "))


  valortotal += v
conversao = valortotal*5.13

print(f"O valor total da sua compra é USD{valortotal}, R${conversao}")

"""# IF/ELSE

1) Faça um código que peça ao usuário digitar o número que corresponde ao mês (1-Janeiro, 2-Fevereiro, 3-Março, 4-Abril etc.) se digitar outro valor da “ERRO”.
"""

mes = input("Digite o dia do mês (1 A 12)")

if mes == "1" and mes == "1":
  print("Estamos em Janiero!")

elif mes == "2" and mes == "2":
  print("Estamos em Fevereiro!")

elif mes == "3" and mes == "3":
  print("Estamos em Março!")

elif mes == "4" and mes == "4":
  print("Estamos em Abril!")

elif mes == "5" and mes == "5":
  print("Estamos em Maio!")

elif mes == "6" and mes == "6":
  print("Estamos em Junho!")

elif mes == "7" and mes == "7":
  print("Estamos em Julho!")

elif mes == "8" and mes == "8":
  print("Estamos em Agosto!")

elif mes == "9" and mes == "9":
  print("Estamos em Setembro!")

elif mes == "10" and mes == "10":
  print("Estamos em Outubro!")

elif mes == "11" and mes == "11":
  print("Estamos em Novembro!")

elif mes == "12" and mes == "12":
  print("Estamos em Dezembro!")

else:
  print("ERRO")

"""2) Calculadora de Índice de Massa Corporal (IMC):

  Crie um código que peca ao usuário para colocar seu peso e altura, e faça o cálculo do IMC:



*   Peso(kg) / altura*altura.


E com o cálculo em mãos, mostre o IMC, sua Classificação e seu Grau de Obesidade, nos seguintes requisitos:

* <= 18,5: Classificacao: Magreza; Grau de Obesidade: 0
* De 18,6 a 24,9: Classificacao: Normal; Grau de Obesidade: 0
* De 25 a 29,9: Classificacao: Sobrepeso; Grau de Obesidade: 1;
* De 30 a 39,9: Classificacao: Obesidade; Grau de Obesidade: 2;
* =>40: Classificacao: Obesidade Grave; Grau de Obesidade: 3;






"""

peso = int(input("Digite seu peso(kg): "))
altura = float(input("Digite sua altura(m): "))
imc = peso/(altura*altura)

if imc <= 18.5:
  print(f"IMC = {imc:,.2f}, CLASSIFICACAO = Magreza, GRAU DE OBESIDADE = 0")
elif 18.6 <= imc <= 24.9:
  print(f"IMC = {imc:,.2f}, CLASSIFICACAO = Normal, GRAU DE OBESIDADE = 0")
elif 25 <= imc <= 29.9:
  print(f"IMC = {imc:,.2f}, CLASSIFICACAO = Sobrepeso, GRAU DE OBESIDADE = 1")
elif 30 <= imc <= 39.9:
  print(f"IMC = {imc:,.2f}, CLASSIFICACAO = Obesidade, GRAU DE OBESIDADE = 2")
else:
  print(f"IMC = {imc:,.2f}, CLASSIFICACAO = Obesidade Grave, GRAU DE OBESIDADE = 3")