# -*- coding: utf-8 -*-
"""WHILE_PT2.

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12WRcwFWYCJ072g7Xyuy2gaJWzUbPY7Ld

# WHILE (PARTE 2)

1) Faça um programa que peça uma nota, entre zero e dez. Mostre uma mensagem
caso o valor seja inválido e continue pedindo até que o usuário informe um valor
válido.
"""

nota = int(input("Digite uma nota entre 0 e 10: "))

while nota <0 or nota >10:
  print("Nota Ínvalida")
  nota = int(input("Digite uma nota entre 0 e 10: "))

print(f"Nota Válida, {nota}")

"""2) Faça um programa que calcule e mostre a média aritmética de N notas."""

soma = 0
contador = 0
quant = int(input("Digite a quantidade de notas: "))

while contador < quant:
  notas = int(input(f"Digite a {contador+1}° nota: "))
  soma += notas
  contador += 1

print(f"A média aritmética das notas foi de: {soma/quant}")

"""3) Faça um programa que leia um nome de usuário e a sua senha e não aceite a
senha igual ao nome do usuário, mostrando uma mensagem de erro e voltando a
pedir as informações.
"""

usuario = input("Digite um usuário: ")
senha = input("Digite uma senha: ")

while usuario == senha:
  print("Obs: O usuário e a senha precisam ser diferentes!")
  usuario = input("Digite um usuário: ")
  senha = input("Digite uma senha: ")

print("Cadastro Aceito")

"""4) A) Um funcionário de uma empresa recebe aumento salarial anualmente.
Sabe-se que: Esse funcionário foi contratado em 1995, com salário inicial de R$
1.000,00; Em 1996 recebeu aumento de 1,5% sobre seu salário inicial; A partir de
1997 (inclusive), os aumentos salariais sempre correspondem ao dobro do
percentual do ano anterior. Faça um programa que determine o salário atual desse
funcionário. Após concluir isto, altere o programa permitindo que o usuário digite o
salário inicial do funcionário.
"""

inicial = 1000
ano_inicial = 1995
ano_atual = 2024
aumento = 1.5 / 100

while ano_inicial != ano_atual:
  ano_inicial += 1
  inicial += inicial*aumento
  aumento *= 2
  print(f"O salário deste individuo no ano de {ano_inicial} é de: R$ {inicial:,.2f}")

"""4) B)Após concluir o exercicio anterior, altere o programa permitindo que o usuário digite o
salário inicial do funcionário.
"""

inicial = float(input("Digite o salário inicial: "))
ano_inicial = 1995
ano_atual = 2024
aumento = 1.5 / 100

while ano_inicial != ano_atual:
  ano_inicial += 1
  inicial += inicial*aumento
  aumento *= 2
  print(f"O salário deste individuo no ano de {ano_inicial} é de: R$ {inicial:,.2f}")

"""5) Faça um programa que leia e valide as seguintes informações:
* Nome: maior que 3 caracteres;
* Idade: entre 0 e 150;
* Salário: maior que zero;
* Sexo: 'f' = feminino ou 'm' = masculino;
* Estado Civil: 's' = solteiro(a), 'c' = casado(a), 'v' = viuvo(a), 'd' = divorciado(a);
"""

nome = input("Digite seu nome:")
idade = int(input("Digite sua idade: "))
while idade < 0:
  print("Tente Novamente")
  idade = int(input("Digite sua idade: "))

salario = float(input("Digite seu salário: "))
while salario <=0:
    print("Valor Ínvalido")
    salario = float(input("Digite seu salário"))

sexo = input("Sexo: ")
while sexo != "M" and sexo != "m" and sexo != "F" and sexo != "f":
      print("Ínvalido")
      sexo = input("Sexo: ")

estado_civil = input("Estado Civil ('S' para solteiro(a); 'C' para casado(a); 'V' para viuvo(a) ou 'D' para divorciado(a)): ")
while estado_civil != "S" and estado_civil != "s" and estado_civil != "C" and estado_civil != "c" and estado_civil != "V" and estado_civil != "v" and estado_civil != "D" and estado_civil != "d":
          print("Ínvalido")
          estado_civil = input("Estado Civil ('S' para solteiro(a); 'C' para casado(a); 'V' para viuvo(a) ou 'D' para divorciado(a)): ")

print(f"Nome: {nome};")
print(f"Idade: {idade} Anos;")
print(f"Salário: R${salario};")
print(f"Sexo: {sexo};")
print(f"Estado Civil: {estado_civil}.")

"""6) Supondo que a população de um país A seja da ordem de 80000 habitantes com
uma taxa anual de crescimento de 3% e que a população de B seja 200000
habitantes com uma taxa de crescimento de 1.5%. Faça um programa que calcule e
escreva o número de anos necessários para que a população do país A ultrapasse
ou iguale a população do país B, mantidas as taxas de crescimento.
"""

PaisA = 80000
PaisB = 200000
cresceA = 3 / 100
cresceB = 1.5 / 100
anos = 0

while PaisA < PaisB:
  anos += 1
  PaisA += PaisA*cresceA
  PaisB += PaisB*cresceB

print(f"A previsão é que daqui {anos} anos. A população do Pais A supera a população do Pais B")

"""7) Faça um programa que calcule o fatorial de um número inteiro fornecido pelo
usuário. Ex.: 5!=5.4.3.2.1=120
"""

fatorial = 1
contador = 1
numero = int(input("Digite um número: "))

while contador <= numero:
  fatorial = fatorial * contador
  contador += 1

print(f"Resultado: {fatorial}")

"""8) Faça um programa que solicite ao usuário números indefinidamente até que ele
digite 0. Em seguida, o programa deve imprimir a média dos números digitados.
"""

soma = 0
contador = 0
numero = int(input("Acerte o número: "))

while numero != 0:
  numero = int(input(f"Tente novamente: "))
  soma += numero
  contador += 1

print(f"A média dos números são {soma/contador}")

"""9) A série de Fibonacci é formada pela sequência 1,1,2,3,5,8,13,21,34,55,... Faça um
programa capaz de gerar a série até o n−ésimo termo.
"""

ultimo = 1
penultimo = 1
contador = 1

print(ultimo)
print(penultimo)

while contador <=9:
  next = ultimo + penultimo
  penultimo = ultimo
  ultimo = next

  contador += 1

  print(next)

"""10) O Sr. Manoel Joaquim expandiu seus negócios para além dos negócios de 1,99 e
agora possui uma loja de conveniências. Faça um programa que implemente uma
caixa registradora rudimentar.

1 - O programa deverá receber um número desconhecido de valores referentes
aos preços das mercadorias. Um valor zero deve ser informado pelo
operador para indicar o final da compra.

2 - O programa deve então mostrar o total da compra e perguntar o valor em
dinheiro que o cliente forneceu, para então calcular e mostrar o valor do
troco. Após esta operação, o programa deverá voltar ao ponto inicial, para
registrar a próxima compra. A saída deve ser conforme o exemplo abaixo:

* Lojas Tabajara
* Produto 1: RS 2.20
* Produto 2: RS 5.80
* Produto 3: RS 0
* Total: RS 9.00
* Dinheiro: RS 20.00
* Troco: RS 11.00
"""

n = 0

total = 0
produto = 0
valor = 0

print("Lojas Tabajara")

while True:
  valor = float(input(f"{n+1}° produto: "))
  total += valor
  produto += 1
  n += 1

  if valor == 0:
     produto = 0
     valor = 0
     print(f"Total = R${total}")
     dinheiro = float(input("Dinheiro: R$"))
     troco = dinheiro - total
     print(f"Troco: {troco}")
     break

"""11) O cardápio de uma lanchonete é o seguinte:
Especificação / Código / Preço

* Cachorro Quente 100 RS 1,20
* Bauru Simples 101 RS 1,30
* Bauru com ovo 102 RS 1,50
* Hambúrguer 103 RS 1,20
* Cheeseburguer 104 RS 1,30
* Refrigerante 105 RS 1,00

Faça um programa que leia o código dos itens pedidos e as quantidades desejadas.
Calcule e mostre o valor a ser pago por item (preço * quantidade) e o total geral do
pedido. Considere que o cliente deve informar quando o pedido deve ser encerrado.
"""

