# -*- coding: utf-8 -*-
"""if_and_else

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15Aisb61HpjYGs6YEVogDYzZqpi2M2RCR

# IF E ELSE

2)	Faça um programa que peça um valor e mostre na tela se o valor é positivo ou negativo:
"""

a = input("Digite um numero ")
a = int(a)
if a > 0:
  print("Positivo")
elif a == 0:
  print("Zero")
else:
  print("Negativo")

"""3) Faça um programa que verifique (usando if e else) se uma letra digitada é “F” ou “M”. Conforme a letra escrever: F – Feminino, M- Masculino, Sexo inválido:"""

sexo = input("Digite M se seu sexo for Masculino ou F se seu sexo for Feminino ")
if sexo == "M" or sexo == "m":
  print("Sexo Masculino")
elif sexo == "F" or sexo == "f":
  print("Sexo Feminino")
else:
  print("Sexo Invalido")

"""4) Faça um programa que verifique (usando if e else) se uma letra digitada é vogal ou consoante:"""

letra = input("Digite uma Letra ")
if letra == "A" or letra == "a" or letra == "E" or letra == "e" or letra == "I" or letra == "i" or letra == "O" or letra == "o" or letra == "U" or letra == "u":
  print("Esta letra é uma vogal")
else:
  print("Esta letra é uma consoante")

"""5) Faça um programa para a leitura de duas notas parciais de um aluno.
* A mensagem “Aprovado”, se a média
alcançada for maior ou igual a sete;
* A mensagem “Aprovado com Distinção”, se a média for igual a dez;
* A mensagem “Reprovado” se a média for menor de do que sete:

"""

parcial1 = int(input("Digite a Primeira Nota "))
parcial2 = int(input("Digite a Segunda Nota "))
final = (parcial1 + parcial2) / 2
if final >= 7 and final <= 9:
  print("Voce esta Aprovado(a)")
  print("Nota = ")
  print(final)
elif final == 10:
  print("Voce esta aprovado com distinção. ")
elif final >10 or final <0:
  print("Erro")
else:
  print("Voce esta Reprovado(a)")
  print("Nota = ")
  print(final)

"""6) Faça um programa que leia três números, verifique (usando if e else), e mostre o maior deles."""

a = int(input("Digite o primeiro numero: "))
b = int(input("Digite o segundo numero: "))
c = int(input("Digite o terceiro numero: "))

if a > b and a > c:
  print(a)
elif b > a and b > c:
  print(b)
else:
 if c > a and c > b:
  print(c)

"""7) Faça um programa que leia três números, verifique (usando if e else) e mostre o maior e o menor deles:"""

maior = 0
menor = 0

n1 = float(input("Digite o Primeiro Numero: "))
n2 = float(input("Digite o Segundo Numero: "))
n3 = float(input("Digite o Terceiro Numero: "))

if n1 >= n2 and n1 >= n3:
   maior = n1
elif n2 >= n1 and n2 >= n3:
   maior = n2
else:
   maior = n3

if n1 <= n2 and n1 <= n3:
   menor = n1
elif n2 <= n1 and n2 <= n3:
   menor = n2
else:
   menor = n3

print("O maior número é:", maior)
print("O menor número é:", menor)

"""8) Faça um programa que pergunte o preço de três produtos e informe qual produto você deve comprar, sabendo que a decisão é sempre o mais barato."""

menor = 0

p1 = float(input("Digite o valor: "))
p2 = float(input("Digite o valor: "))
p3 = float(input("Digite o valor: "))

if p1 <= p2 and p1 <= p3:
  menor = p1

elif p2 <= p1 and p2 <= p3:
  menor = p2

else:
  menor = p3

print("valor: ", menor)

"""9) Faça um programa que leia três números e mostre-os em ordem decrescente."""

9a = float(input("Digite o numero: "))
b = float(input("Digite o numero: "))
c = float(input("Digite o numero: "))

if a >= b >= c:
 print(a, b, c)

elif a >= c >= b:
 print(a, c, b)

elif b >= a >= c:
 print(b, a, c)

elif b >= c >= a:
 print(b, c, a)

elif c >= a >= b:
 print(c, a, b)

else:
  print(c, b, a)

"""10) Faça um programa que pergunte em que turno você estuda. Peça para digitar:
* M-matutino = Imprima a mensagem “Bom dia!”
* V-vespertino = Imprima a mensagem "Boa Tarde"
* N-noturno = Imprima a mensagem “Boa noite”

Senão = Imprima a mensagem "Erro"

"""

periodo = input("Digite seu turno. M-Matutino, V-Vespertino ou N-Noturno")

if periodo == "M" or periodo == "m":
 print("Bom Dia")

elif periodo == "V" or periodo == "v":
 print("Boa Tarde")

elif periodo == "N" or periodo == "n":
 print("Boa Noite")

else:
 print("Erro")

"""11) Faça um programa que peça dois números ao usuário e mostre qual o maior e qual o menor:"""

n1 = float(input("Digite o Primeiro Numero: "))
n2 = float(input("Digite o Segundo Numero: "))

if n1 > n2:
 print("O valor n1 é maior que o valor do n2")

elif n2 > n1:
 print("O valor n2 é maior que o valor do n1")

elif n1 == n2:
  print("Os valores são iguais")

"""12) Faça um Programa que leia um número e exiba o dia correspondente da semana (1- Domingo , 2- Segunda, etc.). Se digitar outro valor deve aparecer “valor inválido" ):"""

calendario = input("Digite o dia da Semana (1 a 7): ")

if calendario == "1" and calendario == "1":
  print("Hoje é Domingo")

elif calendario == "2" and calendario == "2":
  print("Hoje é Segunda-Feira")

elif calendario == "3" and calendario == "3":
  print("Hoje é Terça-Feira")

elif calendario == "4" and calendario == "4":
  print("Hoje é Quarta-Feira")

elif calendario == "5" and calendario == "5":
  print("Hoje é Quinta-Feira")

elif calendario == "6" and calendario == "6":
  print("Hoje é Sexta-Feira")

elif calendario == "7" and calendario == "7":
  print("Hoje é Sabado")

else:
  print("Invalido")